# Generated by Django 3.2.21 on 2023-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('phnum', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni_Profile',
            fields=[
                ('alumniid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('phnum', models.CharField(max_length=10)),
                ('about', models.TextField()),
                ('dob', models.DateField(verbose_name='')),
                ('company', models.CharField(max_length=50)),
                ('sctc', models.IntegerField(max_length=10)),
                ('cctc', models.BigIntegerField(max_length=20)),
                ('aoe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni'), ('Admin', 'Admin')], default='Student', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('studid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('phnum', models.CharField(max_length=10)),
                ('about', models.TextField()),
                ('dob', models.DateField(verbose_name='')),
                ('class_year', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
    ]
